# Generated by Django 5.1.4 on 2025-01-17 09:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("NS", "Not Specified")],
                default="NS",
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+12125552368",
                max_length=30,
                region=None,
                verbose_name="Phone number",
            ),
        ),
    ]
