version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: ./docker/develop/django/Dockerfile
    volumes:
      - .:/app:z
      - static_volume:/app/staticfiles
      - media_volume:/app/medafiles
    expose:
      - "8000"
    env_file:
      - ./.envs/.develop/.django
      - ./.envs/.develop/.postgres
    depends_on:
      - postgres
      - mailhog
      - redis
    command: /start
    networks:
      - blog-api

  postgres:
    build:
      context: .
      dockerfile: ./docker/develop/postgres/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_posgres_data_backups:/backups
    env_file:
      - ./.envs/.develop/.postgres
    networks:
      - blog-api

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - blog-api

  redis:
    image: redis:7-alpine
    networks:
      - blog-api

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/develop/django/Dockerfile
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.envs/.develop/.django
      - ./.envs/.develop/.postgres
    depends_on:
      - redis
      - postgres
      - mailhog
    networks:
      - blog-api

  flower:
    build:
      context: .
      dockerfile: ./docker/develop/django/Dockerfile
    command: /start-flower
    volumes:
      - flower_data:/data
    env_file:
      - ./.envs/.develop/.django
      - ./.envs/.develop/.postgres
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - postgres
    networks:
      - blog-api


  nginx:
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/medafiles
    build:
      context: ./docker/develop/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - blog-api

networks:
  blog-api:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  local_postgres_data: {}
  local_posgres_data_backups: {}
  flower_data: {}